name: assimalign.extensions.validation.configurable.ci

on:
  push:
    branches:
    - main
    - development
    - users/**
    - features/**
    paths: 
    - 'libraries/Validation/src/**'
    - 'libraries/Directory.Build.props'                                                 # When the Global Props File Changes
    - 'libraries/Validation/Directory.Build.props'
    - '.github/workflows/assimalign.extensions.validation.configurable.yml'        # When Pipeline File Changes

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2    
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
        include-prerelease: true
    
    - name: Restore Project
      run: dotnet restore 
      working-directory: './libraries/Validation/src/Assimalign.Extensions.Validation.Configurable'
    
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
      working-directory: './libraries/Validation/src/Assimalign.Extensions.Validation.Configurable'
    
    #   NOTE: Currently No Test Projects for This library
    # - name: Restore Unit Tests Project
    #   run: dotnet restore 
    #   working-directory: './libraries/Validation/tests/Assimalign.Extensions.Validation.Configurable.Tests'

    # - name: Run Unit Tests
    #   run: dotnet test --no-restore --verbosity normal
    #   working-directory: './libraries/Validation/tests/Assimalign.Extensions.Validation.Configurable.Tests'
    
    - name: Publish Nuget Package
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_PUBLISHING_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './libraries/Validation/src/Assimalign.Extensions.Validation.Configurable/bin/Release/'