name: .NET

on:
  push:
    branches: [ main, tags/release/* ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: Setup dotnet 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: Restore Project dependencies
      run: dotnet restore 
      working-directory: './src'
      
    - name: Build Projects
      run: dotnet build --configuration Release --no-restore
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Configuration Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Configuration.Binder Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration.Binder/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Configuration.CommandLine Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration.CommandLine/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Configuration.EnvironmentVariables Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration.EnvironmentVariables/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Configuration.FileExtensions Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration.FileExtensions/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Configuration.Json Nuget
      run: dotnet nuget push "Assimalign.Extensions.Configuration.Json/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.DependencyInjection Nuget
      run: dotnet nuget push "Assimalign.Extensions.DependencyInjection/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.FileSystemGlobbing Nuget
      run: dotnet nuget push "Assimalign.Extensions.FileSystemGlobbing/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
    
    - name: Publish Assimalign.Extensions.FileProviders Nuget
      run: dotnet nuget push "Assimalign.Extensions.FileProviders/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Hosting Nuget
      run: dotnet nuget push "Assimalign.Extensions.Hosting/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Http Nuget
      run: dotnet nuget push "Assimalign.Extensions.Http/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Logging Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Logging.Configuration Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging.Configuration/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Logging.Console Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging.Console/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Logging.Debug Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging.Debug/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Logging.EventLog Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging.EventLog/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Logging.EventSource Nuget
      run: dotnet nuget push "Assimalign.Extensions.Logging.EventSource/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.ObjectPool Nuget
      run: dotnet nuget push "Assimalign.Extensions.ObjectPool/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'

    - name: Publish Assimalign.Extensions.Options Nuget
      run: dotnet nuget push "Assimalign.Extensions.Options/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
      
    - name: Publish Assimalign.Extensions.Primitives Nuget
      run: dotnet nuget push "Assimalign.Extensions.Primitives/**/*.nupkg" -k ${{secrets.NUGET_PUBLISHING_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: './src'
